# config/parameters.py

YEAR = 365
YEAR_QUANTITY = 10

DECREASING_FERTILIZE = 1
DECREASING_HEALTH = 10
DECREASING_WATER = 20
GROWING_HEALTH_THRESHOLD = 30

INCREASE_FERTILIZER = 30
ACTIONS_PER_DAY = 3

HEALTH_WELLCARE = 10
PRUNING_HEALTH_THRESHOLD = 30
PRUNING_DECREASE_BRANCHE = 1

INCREASE_WATER_WATERING = 100
PERCENT_OF_DAYS_TO_PRUNE_REPOT = 0.7

